/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Bitcoin;


import Bank.Customer;
import Bitcoin.Exchanger;
import Business.Business;
import WorkRequest.InvestorWorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liugo
 */
public class BitcoinExchangerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form MatchTransaction
     */
//    public BTPExcahngerWorkAreaJPanel() {
//        initComponents();
//    }
    private JPanel userProcessContainer;
    private Business business;
    private Exchanger exchanger;
    public BitcoinExchangerWorkArea(JPanel userProcessContainer, Business business, Exchanger exchanger) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.exchanger = exchanger;
        jTextFieldExchangerName.setText(exchanger.getName());
        populateSellingTable();
        populateBuyingTable();    
//        int row = jTableSelling.getSelectedRow();
    }
    
    private void populateSellingTable() {
        DefaultTableModel model = (DefaultTableModel) jTableSelling.getModel();
        model.setRowCount(0);
        for(InvestorWorkRequest iwr : business.getExchangerWorkQueue().getWorkRequestList()){
            if(iwr.getMessage().equals("Selling.")){
                Object[] row = new Object[5];
                row[0] = iwr.getSender();
                row[1] = iwr.getRequestDate();
                row[2] = iwr.getStatus();
                row[3] = iwr.getQuantity();
                row[4] = iwr.getMessage();
                model.addRow(row);
            }
        }
    }
    
    private void populateBuyingTable() {
        DefaultTableModel model = (DefaultTableModel) jTableBuying.getModel();
        model.setRowCount(0);
        for(InvestorWorkRequest iwr : business.getExchangerWorkQueue().getWorkRequestList()){
            if(iwr.getMessage().equals("Buying.")){
                Object[] row = new Object[5];
                row[0] = iwr.getSender();
                row[1] = iwr.getRequestDate();
                row[2] = iwr.getStatus();
                row[3] = iwr.getQuantity();
                row[4] = iwr.getMessage();
                model.addRow(row);
            }
        }  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldSellingQuantity = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBuying = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSelling = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButtonSendConfirmation = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButtonSelectSelling = new javax.swing.JButton();
        jButtonMatchingBuyer = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldSellerName = new javax.swing.JTextField();
        jTextFieldBuyerName = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldBuyingQuantity = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldExchangerName = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldBuyingDate = new javax.swing.JTextField();
        jTextFieldSellingDate = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jButtonCheckConfirmFromInvestor = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 153));

        jLabel31.setText("Selling Quantity:");

        jLabel12.setText("|");

        jLabel11.setText("|");

        jLabel28.setText("-------Buying--------------------------------------------------------------------------------------------------");

        jLabel10.setText("|");

        jLabel9.setText("|");

        jLabel8.setText("|");

        jLabel7.setText("|");

        jLabel6.setText("|");

        jLabel5.setText("|");

        jLabel4.setText("|");

        jLabel3.setText("|");

        jTableBuying.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Investor", "Date", "Status", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableBuying);
        if (jTableBuying.getColumnModel().getColumnCount() > 0) {
            jTableBuying.getColumnModel().getColumn(0).setResizable(false);
            jTableBuying.getColumnModel().getColumn(1).setResizable(false);
            jTableBuying.getColumnModel().getColumn(2).setResizable(false);
            jTableBuying.getColumnModel().getColumn(3).setResizable(false);
            jTableBuying.getColumnModel().getColumn(4).setResizable(false);
        }

        jTableSelling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Investor", "Date", "Status", "Quantity", "Direction"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableSelling);
        if (jTableSelling.getColumnModel().getColumnCount() > 0) {
            jTableSelling.getColumnModel().getColumn(0).setResizable(false);
            jTableSelling.getColumnModel().getColumn(1).setResizable(false);
            jTableSelling.getColumnModel().getColumn(2).setResizable(false);
            jTableSelling.getColumnModel().getColumn(3).setResizable(false);
            jTableSelling.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel37.setText("|");

        jLabel16.setText("|");

        jLabel15.setText("|");

        jButtonSendConfirmation.setBackground(new java.awt.Color(255, 0, 51));
        jButtonSendConfirmation.setForeground(new java.awt.Color(255, 0, 0));
        jButtonSendConfirmation.setText("Send confirmation to Investor");
        jButtonSendConfirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendConfirmationActionPerformed(evt);
            }
        });

        jLabel14.setText("|");

        jLabel2.setText("|");

        jLabel13.setText("|");

        jLabel26.setText("-------Selling----------------------------------------------------------------------------------------------------");

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel17.setText("Match Transaction");

        jLabel19.setText("|");

        jButtonSelectSelling.setBackground(new java.awt.Color(255, 0, 51));
        jButtonSelectSelling.setForeground(new java.awt.Color(255, 0, 0));
        jButtonSelectSelling.setText("Select a seller");
        jButtonSelectSelling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectSellingActionPerformed(evt);
            }
        });

        jButtonMatchingBuyer.setBackground(new java.awt.Color(255, 0, 0));
        jButtonMatchingBuyer.setForeground(new java.awt.Color(255, 0, 0));
        jButtonMatchingBuyer.setText("Match Buyer");
        jButtonMatchingBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMatchingBuyerActionPerformed(evt);
            }
        });

        jLabel33.setText("Selling Investor Name:");

        jLabel34.setText("Matching Buyer Name:");

        jLabel35.setText("Buying Quantity:");

        jLabel18.setText("Exchanger Name:");

        jTextFieldExchangerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldExchangerNameActionPerformed(evt);
            }
        });

        jLabel36.setText("Buying Date:");

        jTextFieldBuyingDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuyingDateActionPerformed(evt);
            }
        });

        jLabel32.setText("Selling Date:");

        jButtonCheckConfirmFromInvestor.setBackground(new java.awt.Color(255, 0, 51));
        jButtonCheckConfirmFromInvestor.setForeground(new java.awt.Color(255, 0, 0));
        jButtonCheckConfirmFromInvestor.setText("Check Investor Confirmation");
        jButtonCheckConfirmFromInvestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckConfirmFromInvestorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(jButtonSelectSelling)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldExchangerName, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)
                                .addComponent(jLabel37))
                            .addComponent(jLabel19))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel28)))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldBuyerName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSellerName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSendConfirmation)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldBuyingQuantity))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldSellingQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldBuyingDate))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldSellingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMatchingBuyer)))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCheckConfirmFromInvestor)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldExchangerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel26))
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSelectSelling)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(jTextFieldSellingQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)
                            .addComponent(jTextFieldSellerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(jTextFieldBuyingQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(jTextFieldBuyerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jTextFieldSellingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMatchingBuyer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(jTextFieldBuyingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(jButtonSendConfirmation)
                .addGap(16, 16, 16)
                .addComponent(jButtonCheckConfirmFromInvestor)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldExchangerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldExchangerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldExchangerNameActionPerformed

    private void jButtonSelectSellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectSellingActionPerformed
        // TODO add your handling code here:
        jButtonSelectSelling.setEnabled(false);
        int row = jTableSelling.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            jButtonSelectSelling.setEnabled(true);
            return;
        }
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
        Date datesell = (Date) jTableSelling.getValueAt(row, 1);
        String date1 = df.format(datesell);
        Customer investorSell = (Customer) jTableSelling.getValueAt(row, 0);
        int sellingQuantity = (int) jTableSelling.getValueAt(row, 3);
        jTextFieldSellerName.setText(investorSell.getName());
        jTextFieldSellingQuantity.setText(String.valueOf(sellingQuantity));
        jTextFieldSellingDate.setText(date1);
    }//GEN-LAST:event_jButtonSelectSellingActionPerformed

    private void jTextFieldBuyingDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuyingDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuyingDateActionPerformed

    private void jButtonMatchingBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatchingBuyerActionPerformed
        // TODO add your handling code here:
        jButtonMatchingBuyer.setEnabled(false);
        int j = Integer.parseInt(jTextFieldSellingQuantity.getText());
        for(InvestorWorkRequest iwr : business.getExchangerWorkQueue().getWorkRequestList()){
            if(iwr.getMessage().equals("Buying.")){
                if(iwr.getQuantity()<=j){
                    for(int i = 0; i <= j; i++){
                        if(iwr.getQuantity() + i == j){
                            DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
                            Date datebuy = (Date)iwr.getRequestDate();
                            String date1 = df.format(datebuy);
                            jTextFieldBuyerName.setText(iwr.getSender().getName());
                            jTextFieldBuyingQuantity.setText(String.valueOf(iwr.getQuantity()));
                            jTextFieldBuyingDate.setText(date1);
                        }break;
                    }
                }
            }
        }
        
    }//GEN-LAST:event_jButtonMatchingBuyerActionPerformed

    private void jButtonSendConfirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendConfirmationActionPerformed
        // TODO add your handling code here:
        Date date = new Date();
        String sellerName = jTextFieldSellerName.getText();
        String sellingQuantity = jTextFieldSellingQuantity.getText();
        int sellingQ = Integer.parseInt(sellingQuantity);
        String sellerDate = jTextFieldSellingDate.getText();
        String buyerName = jTextFieldBuyerName.getText();
        String buyingQuantity = jTextFieldBuyingQuantity.getText();
        int buyingQ = Integer.parseInt(buyingQuantity);
        String buyerDate = jTextFieldBuyingDate.getText();
//        for(Customer cusS : business.getCustomerDirectory().getCustomerDirectory()){
//            if(cusS.getName().equals(sellerName)){
//                Customer seller = cusS;
//            }
//        }
        business.getMatchPairDirectory().createMatchPair(sellerName, buyerName, sellingQ, buyingQ, buyingQ*1200, date, "Waiting.", "Waiting.");
        jButtonSelectSelling.setEnabled(true);
        jButtonMatchingBuyer.setEnabled(true);
        
        jTextFieldSellerName.setText("");
        jTextFieldSellingQuantity.setText("");
        jTextFieldSellingDate.setText("");
        jTextFieldBuyerName.setText("");
        jTextFieldBuyingQuantity.setText("");
        jTextFieldBuyingDate.setText("");
        
    }//GEN-LAST:event_jButtonSendConfirmationActionPerformed

    private void jButtonCheckConfirmFromInvestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckConfirmFromInvestorActionPerformed
        // TODO add your handling code here:
        BuildTransactionjPanel btjp = new BuildTransactionjPanel(userProcessContainer, business, exchanger);
        userProcessContainer.add("BuildTransactionjPanel", btjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButtonCheckConfirmFromInvestorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheckConfirmFromInvestor;
    private javax.swing.JButton jButtonMatchingBuyer;
    private javax.swing.JButton jButtonSelectSelling;
    private javax.swing.JButton jButtonSendConfirmation;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableBuying;
    private javax.swing.JTable jTableSelling;
    private javax.swing.JTextField jTextFieldBuyerName;
    private javax.swing.JTextField jTextFieldBuyingDate;
    private javax.swing.JTextField jTextFieldBuyingQuantity;
    private javax.swing.JTextField jTextFieldExchangerName;
    private javax.swing.JTextField jTextFieldSellerName;
    private javax.swing.JTextField jTextFieldSellingDate;
    private javax.swing.JTextField jTextFieldSellingQuantity;
    // End of variables declaration//GEN-END:variables

   

   
}
