/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Supplier;

import Business.Business;
import Supplier.SaleRecord;
import UserInterface.Bank.SupplierAccount.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author owner
 */
public class SupplierAccountmanagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupplierAccountmanagementJPanel
     */
//    public SupplierAccountmanagementJPanel() {
//        initComponents();
//    }
    private JPanel userProcessContainer;
    private Business business;
    
    public SupplierAccountmanagementJPanel(JPanel userProcessContainer, Business business) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.business = business;
       supplierAccountNumberjTextField.setText(business.getSupplierAccount().getAccountnumber());
       supplierBankjTextField.setText(business.getSupplierAccount().getBankname());
       showTotalBalance();
       populatesaleRecordTable();
       
    }
    
    private void showTotalBalance() {
       int tBalance = 0;
       for(SaleRecord sr : business.getSupplierAccount().getSaleRecordList()){
           int rBalance = sr.getQuantity()*1200;
           tBalance = tBalance + rBalance;
       }
       supplierbalancejTextField.setText(String.valueOf(tBalance));
    }
    private void populatesaleRecordTable() {
        DefaultTableModel model = (DefaultTableModel)saleRecordJTable.getModel();
        model.setRowCount(0);
        for (SaleRecord sr : business.getSupplierAccount().getSaleRecordList()){
            Object[] row = new Object[5];
            row[0] = sr.getId();
            row[1] = sr.getInvestor().getName();
            row[2] = sr.getQuantity();
            row[3] = sr.getQuantity()*1200;
            row[4] = sr.getDate();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        supplierAccountNumberjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        supplierbalancejTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        saleRecordJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        supplierBankjTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        backjButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 153));

        jLabel5.setText("Account Number:");

        supplierAccountNumberjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierAccountNumberjTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Balance:");

        supplierbalancejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierbalancejTextFieldActionPerformed(evt);
            }
        });

        saleRecordJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Investor", "Quantity", "Total", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(saleRecordJTable);

        jLabel2.setText("Bank Name:");

        supplierBankjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierBankjTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Supplier Selling Information");

        backjButton1.setText("<< Back");
        backjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("(Total Income)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backjButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(supplierBankjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(supplierAccountNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(supplierbalancejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplierBankjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(supplierAccountNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(supplierbalancejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(backjButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void supplierAccountNumberjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierAccountNumberjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierAccountNumberjTextFieldActionPerformed

    private void supplierbalancejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierbalancejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierbalancejTextFieldActionPerformed

    private void supplierBankjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierBankjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierBankjTextFieldActionPerformed

    private void backjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable saleRecordJTable;
    private javax.swing.JTextField supplierAccountNumberjTextField;
    private javax.swing.JTextField supplierBankjTextField;
    private javax.swing.JTextField supplierbalancejTextField;
    // End of variables declaration//GEN-END:variables

    

    
}
