/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Bank.Admin;

import Business.Business;
import UserInterface.Bank.SupplierAccount.SuppliermanagementJPanel;
import UserInterface.Supplier.SupplierAccountmanagementJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author owner
 */
public class BankAdminWorkArea extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Business business;
    /** Creates new form AdminWorkAreaJPanel */
    public BankAdminWorkArea(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageBitcoinSupplierJButton = new javax.swing.JButton();
        manageBankJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        manageCustomerJButton1 = new javax.swing.JButton();
        manageAccountingPeopleJPanel = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Bank Adminstrative Work Area");

        manageBitcoinSupplierJButton.setText("Manage Bitcoin Supplier Account");
        manageBitcoinSupplierJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBitcoinSupplierJButtonActionPerformed(evt);
            }
        });

        manageBankJButton.setText("Manage Banks");
        manageBankJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBankJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("-Please Select Your Work Responsibility First------------------------------------------------------------------------------------------------");

        manageCustomerJButton1.setText("Manage Customers");
        manageCustomerJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerJButton1ActionPerformed(evt);
            }
        });

        manageAccountingPeopleJPanel.setText("Manage Accounting People");
        manageAccountingPeopleJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccountingPeopleJPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageBitcoinSupplierJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageBankJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(manageCustomerJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageAccountingPeopleJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageCustomerJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageBankJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageAccountingPeopleJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageBitcoinSupplierJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageBitcoinSupplierJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBitcoinSupplierJButtonActionPerformed

        SuppliermanagementJPanel manageParticipantJPanel = new SuppliermanagementJPanel(userProcessContainer, business);
        userProcessContainer.add("SuppliermanagementJPanel", manageParticipantJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageBitcoinSupplierJButtonActionPerformed

    private void manageBankJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBankJButtonActionPerformed

        ManageBankJPanel manageOrganizationJPanel = new ManageBankJPanel(userProcessContainer, business);
        userProcessContainer.add("ManageBankJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageBankJButtonActionPerformed

    private void manageCustomerJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerJButton1ActionPerformed
        // TODO add your handling code here:
        CustomermanagementJPanel manageOrganizationJPanel = new CustomermanagementJPanel(userProcessContainer, business);
        userProcessContainer.add("CustomermanagementJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCustomerJButton1ActionPerformed

    private void manageAccountingPeopleJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccountingPeopleJPanelActionPerformed
        // TODO add your handling code here:
        BankAccountingPeoplemanagementJPanel manageOrganizationJPanel = new BankAccountingPeoplemanagementJPanel(userProcessContainer, business);
        userProcessContainer.add("BankAccountingPeoplemanagementJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAccountingPeopleJPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageAccountingPeopleJPanel;
    private javax.swing.JButton manageBankJButton;
    private javax.swing.JButton manageBitcoinSupplierJButton;
    private javax.swing.JButton manageCustomerJButton1;
    // End of variables declaration//GEN-END:variables
}
