/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Bank.Admin;

import Bank.Bank;
import Bank.BankAccount;
import Bank.BankTransactionRecord;
import Bank.Customer;
import Business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author owner
 */
public class ViewBankAccountTransactionRecords extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomerInfromationJPanel
     */
    private JPanel userProcessContainer;
    private Business business;
    private BankAccount bankaccount;
    private Customer customer;

    public ViewBankAccountTransactionRecords(JPanel container, Business business, Customer customer, BankAccount bankaccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.bankaccount = bankaccount;
        this.customer = customer;
        cnTf.setText(customer.getName());
        anTf.setText(String.valueOf(bankaccount.getAccountNumber()));
        populateTable();
    }
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) trTable.getModel();
        
        model.setRowCount(0);
        
        for (BankTransactionRecord btr : bankaccount.getTransactionRecordDirectory().getFundsTransactionDirectory()){
            Object[] row = new Object[8];
            row[0] = btr.getDate();
            row[1] = btr.getSenderBank();
            row[2] = btr.getSenderAccountNumber();
            row[3] = btr.getSenderName();
            row[4] = btr.getReceiverBank();
            row[5] = btr.getReceiverAccountNumber();
            row[6] = btr.getReceiverName();
            row[7] = btr.getFee();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        trTable = new javax.swing.JTable();
        cnTf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        createUserJButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        anTf = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 153));

        trTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "SenderBankName", "SenderAccountNumber", "SenderName", "ReceiverBank", "ReceiverAccountNumber", "ReceiverName", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(trTable);
        if (trTable.getColumnModel().getColumnCount() > 0) {
            trTable.getColumnModel().getColumn(0).setResizable(false);
            trTable.getColumnModel().getColumn(1).setResizable(false);
            trTable.getColumnModel().getColumn(2).setResizable(false);
            trTable.getColumnModel().getColumn(3).setResizable(false);
            trTable.getColumnModel().getColumn(4).setResizable(false);
            trTable.getColumnModel().getColumn(5).setResizable(false);
            trTable.getColumnModel().getColumn(6).setResizable(false);
            trTable.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel3.setText("Customer Name:");

        jLabel6.setText("-View Customer Bank Account Transaction Records--------------------------------------------------------------------------------------------------------------------");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Transaction Records");

        createUserJButton2.setText("<< Back");
        createUserJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserJButton2ActionPerformed(evt);
            }
        });

        jLabel14.setText("AccountNumebr:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createUserJButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(anTf))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cnTf, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cnTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(anTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(createUserJButton2)
                .addGap(77, 77, 77))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createUserJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserJButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_createUserJButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anTf;
    private javax.swing.JTextField cnTf;
    private javax.swing.JButton createUserJButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable trTable;
    // End of variables declaration//GEN-END:variables
}
