/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Bitcoin.Admin;

import Bitcoin.Custodian;
import Business.Business;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author owner
 */
public class BitcoinCustodianManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
//    public BitcoinCustodianManagementJPanel() {
//        initComponents();
//    }
    private JPanel userProcessContainer;
    private Business business;
    
    BitcoinCustodianManagementJPanel(JPanel userProcessContainer, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        populateCusTable();
    }
    private void populateCusTable() {
        DefaultTableModel model = (DefaultTableModel) custodianJTable.getModel();
        model.setRowCount(0);
        for (Custodian cus : business.getCustodianDirectory().getCustodianDirectory()){
            Object[] row = new Object[2];
            row[0] = cus.getId();
            row[1] = cus;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        custodianJTable = new javax.swing.JTable();
        deleteCusjButton = new javax.swing.JButton();
        createCusjButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cusRealNamejTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cusUNamejTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cusPasswordjTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 153));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("Bitcoin Custodian Management");

        jLabel3.setText("-Create Custodian----------------------------------------------------------------------------------------------------------------------------------------------------");

        custodianJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Custodian Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(custodianJTable);

        deleteCusjButton.setText("Delete Custodian");
        deleteCusjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCusjButtonActionPerformed(evt);
            }
        });

        createCusjButton.setText("Create New Custodian");
        createCusjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCusjButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("-View Custodian Information----------------------------------------------------------------------------------------------------------------------------------------");

        jLabel6.setText("Custodian Name:");

        cusRealNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusRealNamejTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("User Name:");

        cusUNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusUNamejTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Password:");

        cusPasswordjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusPasswordjTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(backJButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(deleteCusjButton)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cusRealNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cusPasswordjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(cusUNamejTextField))
                .addGap(18, 18, 18)
                .addComponent(createCusjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteCusjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusRealNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cusUNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusPasswordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(createCusjButton))
                .addGap(65, 65, 65)
                .addComponent(backJButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void deleteCusjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCusjButtonActionPerformed
        // TODO add your handling code here:
        int row = custodianJTable.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Custodian bitCus = (Custodian) custodianJTable.getValueAt(row, 1);
        business.getCustodianDirectory().getCustodianDirectory().remove(bitCus);
    }//GEN-LAST:event_deleteCusjButtonActionPerformed

    private void createCusjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCusjButtonActionPerformed
        // TODO add your handling code here:
        String realName = cusRealNamejTextField.getText();
        String username = cusUNamejTextField.getText();
        String password = cusPasswordjTextField.getText();
        business.getCustodianDirectory().createCustodian(realName, username, password);
        
        cusRealNamejTextField.setText("");
        cusUNamejTextField.setText("");
        cusPasswordjTextField.setText("");
    }//GEN-LAST:event_createCusjButtonActionPerformed

    private void cusRealNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusRealNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusRealNamejTextFieldActionPerformed

    private void cusUNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusUNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusUNamejTextFieldActionPerformed

    private void cusPasswordjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusPasswordjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusPasswordjTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createCusjButton;
    private javax.swing.JTextField cusPasswordjTextField;
    private javax.swing.JTextField cusRealNamejTextField;
    private javax.swing.JTextField cusUNamejTextField;
    private javax.swing.JTable custodianJTable;
    private javax.swing.JButton deleteCusjButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
