/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Bitcoin.Investor;

import Bank.Customer;
import Business.Business;
import UserInterface.Bitcoin.*;
import WorkRequest.InvestorWorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author liugo
 */
public class StartATransaction extends javax.swing.JPanel {

    /**
     * Creates new form StartATransaction
     */
    private JPanel userProcessContainer;
    private Business business;
    private Customer customer;
    
//    public StartATransaction() {
//        initComponents();
//        this.userProcessContainer = userProcessContainer;
//        this.business = business;
//        this.customer = customer;
//    }

    StartATransaction(JPanel userProcessContainer, Business business, Customer customer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.customer = customer;
        jTextFieldBitcoinCapacity.setText(String.valueOf(customer.getWallet().getBitcoinCatalog().size()));
        jTextFieldBalance.setText(String.valueOf(customer.getBitcoinSystemBalance()));
        jTextFieldSellingPrice.setText(String.valueOf(1200));
        jTextFieldBuyingPrice.setText(String.valueOf(1200));
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldSellingPrice = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldSellingQuantity = new javax.swing.JTextField();
        jTextFieldSellingTotlalPrice = new javax.swing.JTextField();
        jTextFieldTotalBuyingPrice = new javax.swing.JTextField();
        jTextFieldBuyingQuantity = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextFieldBuyingPrice = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jButtonSendREquestToCusAsSeller = new javax.swing.JButton();
        jButtonSendREquestToCusAsBuyer = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextFieldBitcoinCapacity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldBalance = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Start a Transaction");

        jLabel26.setText("-------Selling-----------------------------------------------------------------------------------------------");

        jLabel28.setText("-------Buying------------------------------------------------------------------------------------------------");

        jLabel29.setText("Selling Price:");

        jLabel30.setText("Total Price:");

        jLabel31.setText("Selling Quantity:");

        jTextFieldSellingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSellingPriceActionPerformed(evt);
            }
        });

        jLabel32.setText("BTC");

        jLabel33.setText("BTC");

        jLabel34.setText("Buying Quantity:");

        jLabel35.setText("Total Price:");

        jLabel36.setText("Buying Price:");

        jButtonSendREquestToCusAsSeller.setBackground(new java.awt.Color(255, 204, 204));
        jButtonSendREquestToCusAsSeller.setText("Send Request to Custodian");
        jButtonSendREquestToCusAsSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendREquestToCusAsSellerActionPerformed(evt);
            }
        });

        jButtonSendREquestToCusAsBuyer.setBackground(new java.awt.Color(255, 204, 204));
        jButtonSendREquestToCusAsBuyer.setText("Send Request to Custodian");
        jButtonSendREquestToCusAsBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendREquestToCusAsBuyerActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setText("<< Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Bitcoin Capacity:");

        jLabel5.setText("Balance:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonSendREquestToCusAsBuyer)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldTotalBuyingPrice))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldBuyingQuantity))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldBuyingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel33))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel26)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldBitcoinCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(79, 79, 79)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldSellingTotlalPrice)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jTextFieldSellingQuantity))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jTextFieldSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jButtonSendREquestToCusAsSeller)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldBitcoinCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextFieldSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextFieldSellingQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jTextFieldSellingTotlalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jButtonSendREquestToCusAsSeller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jTextFieldBuyingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jTextFieldBuyingQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jTextFieldTotalBuyingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSendREquestToCusAsBuyer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSendREquestToCusAsSellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendREquestToCusAsSellerActionPerformed
        // TODO add your handling code here:
        Date requestDate = new Date();
        InvestorWorkRequest iWRSelling = new InvestorWorkRequest();
        int sellingQuantity = Integer.parseInt(jTextFieldSellingQuantity.getText());
        iWRSelling.setMessage("Selling.");
        iWRSelling.setSender(customer);
        iWRSelling.setQuantity(sellingQuantity);
        iWRSelling.setRequestDate(requestDate);
        iWRSelling.setStatus("Processing.");
        business.getCustodianWorkQueue().getWorkRequestList().add(iWRSelling);
        
    }//GEN-LAST:event_jButtonSendREquestToCusAsSellerActionPerformed

    private void jButtonSendREquestToCusAsBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendREquestToCusAsBuyerActionPerformed
        // TODO add your handling code here:
        if(customer.getBitcoinSystemBalance()%1200<=100){
            JOptionPane.showMessageDialog(null, "Please recharge your balance or you can't buy bitcoins!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Date requestDate = new Date();
        InvestorWorkRequest iWRBuying = new InvestorWorkRequest();
        int buyingQuantity = Integer.parseInt(jTextFieldBuyingQuantity.getText());
        iWRBuying.setMessage("Buying.");
        iWRBuying.setSender(customer);
        iWRBuying.setQuantity(buyingQuantity);
        iWRBuying.setRequestDate(requestDate);
        iWRBuying.setStatus("Processing.");
        business.getCustodianWorkQueue().getWorkRequestList().add(iWRBuying);
    }//GEN-LAST:event_jButtonSendREquestToCusAsBuyerActionPerformed

    private void jTextFieldSellingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSellingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSellingPriceActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonSendREquestToCusAsBuyer;
    private javax.swing.JButton jButtonSendREquestToCusAsSeller;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldBalance;
    private javax.swing.JTextField jTextFieldBitcoinCapacity;
    private javax.swing.JTextField jTextFieldBuyingPrice;
    private javax.swing.JTextField jTextFieldBuyingQuantity;
    private javax.swing.JTextField jTextFieldSellingPrice;
    private javax.swing.JTextField jTextFieldSellingQuantity;
    private javax.swing.JTextField jTextFieldSellingTotlalPrice;
    private javax.swing.JTextField jTextFieldTotalBuyingPrice;
    // End of variables declaration//GEN-END:variables
}
