/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Bitcoin.Investor;

import Bank.Customer;
import Bitcoin.Transaction;
import Business.Business;
import UserInterface.Bitcoin.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liugo
 */
public class ViewTransaction extends javax.swing.JPanel {

    /**
     * Creates new form dailyTransaction
     */
//    public DailyTransaction() {
//        initComponents();
//    }
    private JPanel userProcessContainer;
    private Business business;
    private Customer customer;
    
    ViewTransaction(JPanel userProcessContainer, Business business, Customer customer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.customer = customer;
        populateTransactionTable();
        jTextFieldSellingBit.setText(String.valueOf(1));
        jTextFieldbuyingBit.setText(String.valueOf(1));
        jTextFieldBuyingUSD.setText(String.valueOf(1200));
        jTextFieldSellingUSD.setText(String.valueOf(1200));
        populateTotal();
    }
    
    private void populateTotal() {
        int totalQuantity = 0;
//        int totalPrice = 0;
        for(Transaction tran : business.getTransactionDirectory().getTransactionDirectory()){
            totalQuantity = totalQuantity + tran.getQuantity();
        }
        jTextFieldTotalBit.setText(String.valueOf(totalQuantity));
        jTextFieldTotalUSD.setText(String.valueOf(totalQuantity*1200));
    }
    
    private void populateTransactionTable() {
        DefaultTableModel model = (DefaultTableModel)transactionjTable.getModel();
        model.setRowCount(0);
        for(Transaction tran : business.getTransactionDirectory().getTransactionDirectory()){
            Object[] row = new Object[5];
            row[0] = tran.getDate();
            row[2] = tran.getBuyer();
            row[1] = tran.getSeller();
            row[3] = tran.getQuantity();
            row[4] = tran.getQuantity()*1200;
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionjTable = new javax.swing.JTable();
        jTextFieldbuyingBit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBuyingUSD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSellingUSD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSellingBit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTotalBit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTotalUSD = new javax.swing.JTextField();
        jButtonStartATran = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Transaction Hall");

        transactionjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time", "Seller", "Buyer", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(transactionjTable);
        if (transactionjTable.getColumnModel().getColumnCount() > 0) {
            transactionjTable.getColumnModel().getColumn(0).setResizable(false);
            transactionjTable.getColumnModel().getColumn(1).setResizable(false);
            transactionjTable.getColumnModel().getColumn(2).setResizable(false);
            transactionjTable.getColumnModel().getColumn(3).setResizable(false);
            transactionjTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jTextFieldbuyingBit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldbuyingBitActionPerformed(evt);
            }
        });

        jLabel2.setText("BTC =");

        jLabel3.setText("USD");

        jTextFieldBuyingUSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuyingUSDActionPerformed(evt);
            }
        });

        jLabel4.setText("---Buying Price------------------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel5.setText("---Selling Price------------------------------------------------------------------------------------------------------------------------------------------------------");

        jTextFieldSellingUSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSellingUSDActionPerformed(evt);
            }
        });

        jLabel6.setText("USD");

        jLabel7.setText("BTC =");

        jTextFieldSellingBit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSellingBitActionPerformed(evt);
            }
        });

        jLabel8.setText("---Total Transaction Price-----------------------------------------------------------------------------------------------------------------------------------------");

        jTextFieldTotalBit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalBitActionPerformed(evt);
            }
        });

        jLabel9.setText("BTC =");

        jLabel10.setText("USD");

        jTextFieldTotalUSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalUSDActionPerformed(evt);
            }
        });

        jButtonStartATran.setText("Start A Transaction");
        jButtonStartATran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartATranActionPerformed(evt);
            }
        });

        jButtonBack.setText("<< Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonStartATran)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextFieldTotalBit, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldTotalUSD, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel10))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextFieldSellingBit, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldSellingUSD, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6))
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextFieldbuyingBit, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldBuyingUSD, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBack)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldbuyingBit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldBuyingUSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSellingBit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldSellingUSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTotalBit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldTotalUSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jButtonStartATran)
                .addGap(21, 21, 21)
                .addComponent(jButtonBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldbuyingBitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldbuyingBitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldbuyingBitActionPerformed

    private void jTextFieldBuyingUSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuyingUSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuyingUSDActionPerformed

    private void jTextFieldSellingUSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSellingUSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSellingUSDActionPerformed

    private void jTextFieldSellingBitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSellingBitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSellingBitActionPerformed

    private void jTextFieldTotalBitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalBitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalBitActionPerformed

    private void jTextFieldTotalUSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalUSDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalUSDActionPerformed

    private void jButtonStartATranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartATranActionPerformed
        // TODO add your handling code here:
        StartATransaction satjp = new StartATransaction(userProcessContainer, business, customer);
        userProcessContainer.add("StartATransaction", satjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButtonStartATranActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonStartATran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldBuyingUSD;
    private javax.swing.JTextField jTextFieldSellingBit;
    private javax.swing.JTextField jTextFieldSellingUSD;
    private javax.swing.JTextField jTextFieldTotalBit;
    private javax.swing.JTextField jTextFieldTotalUSD;
    private javax.swing.JTextField jTextFieldbuyingBit;
    private javax.swing.JTable transactionjTable;
    // End of variables declaration//GEN-END:variables

   

    
}
