/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Bank.Customer;

import Bank.Bank;
import Bank.BankAccount;
import Bank.BankTransactionRecord;
import Bank.Customer;
import Business.Business;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author owner
 */
public class CustomerMakeTransactionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerMakeTransactionJPanel
     */
    private JPanel userProcessContainer;
    private Business business;
    private Customer customer;
    private BankAccount baa = new BankAccount();
    public CustomerMakeTransactionJPanel(JPanel userProcessContainer, Business business, Customer customer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.customer = customer;
        populateCombo1();
        snTf.setText(customer.getName());
        populteCombo2();
    }
    public void populateCombo1() {
        bnCombo1.removeAllItems();

        ArrayList<String> bankname = new ArrayList<String>();
        for (BankAccount ba : customer.getBankAccountList()) {
            if (bankname.isEmpty()) {
                bankname.add(ba.getBankName());
            } else {
                for (int i = 0; i < bankname.size(); i++) {
                    if (ba.getBankName().equals(bankname.get(i)))
                        break;
                    bankname.add(ba.getBankName());
                }
            }
        }
        for (String ss : bankname)
            bnCombo1.addItem(ss);
        
    }
    public void populteCombo2() {
        anCombo1.removeAllItems();
        String bankname = (String) bnCombo1.getSelectedItem();
        for (BankAccount ba : customer.getBankAccountList()) {
            if (ba.getBankName().equals(bankname))
                anCombo1.addItem(String.valueOf(ba.getAccountNumber()));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rnTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        amountTf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bnCombo1 = new javax.swing.JComboBox<>();
        snTf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        bTf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        anCombo1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pwTf = new javax.swing.JTextField();
        anTf = new javax.swing.JTextField();
        bnTf = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        jLabel5.setText("jLabel5");

        setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Make Transaction");

        jLabel4.setText("-----------------------------------------------------From Your Account------------------------------------------------");

        jLabel7.setText("----------------------------------------------------To Another Account------------------------------------------------");

        jLabel3.setText("Bank Name:");

        rnTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnTfActionPerformed(evt);
            }
        });

        jLabel8.setText("Reciever Name:");

        jLabel9.setText("Amount:");

        amountTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTfActionPerformed(evt);
            }
        });

        jLabel10.setText("Account Number:");

        jButton1.setText("Make Transfer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        snTf.setEnabled(false);
        snTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snTfActionPerformed(evt);
            }
        });

        jLabel11.setText("Sender Name:");

        jLabel12.setText("Balance:");

        bTf.setEnabled(false);
        bTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTfActionPerformed(evt);
            }
        });

        jLabel13.setText("Account Number:");

        anCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anCombo1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Bank Name:");

        jLabel15.setText("Password:");

        pwTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bnCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pwTf, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(snTf, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(anCombo1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bTf, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(rnTf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(amountTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(anTf, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bnTf, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(bnCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(snTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(anCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(bTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(pwTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bnTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rnTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(anTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(amountTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rnTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rnTfActionPerformed

    private void amountTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTfActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void snTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snTfActionPerformed

    private void bTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bTfActionPerformed

    private void pwTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwTfActionPerformed

    private void anCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anCombo1ActionPerformed
        // TODO add your handling code here:
        int an = anCombo1.getSelectedIndex();
        for (BankAccount ba : customer.getBankAccountList()) {
            if (ba.getAccountNumber() == an) {
                bTf.setText(String.valueOf(ba.getBalance()));
                baa = ba;
            }
        }
    }//GEN-LAST:event_anCombo1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String password = pwTf.getText();
        int amount = Integer.parseInt(amountTf.getText());
        if (baa.getPassword().equals(password)) {
            if (baa.getBalance() < amount) {
                JOptionPane.showMessageDialog(null, "Your balance is not enough!");
            } else {
                String bankname = bnTf.getText();
                String receiver = rnTf.getText();
                int an = Integer.parseInt(anTf.getText());
                BankAccount rBa = business.getBankAccountDirectory().searchBankAccount(an);
                if (receiver.equals(rBa.getCustomerName())) {
                    BankTransactionRecord left = new BankTransactionRecord();
                    BankTransactionRecord right = new BankTransactionRecord();
                    left.setAccountNumber(baa.getAccountNumber());
                    left.setCustomer(baa.getCustomerName());
                    left.setDate(new Date());
                    left.setDirection("Out");
                    left.setFee(amount);
                    left.setReceiverAccountNumber(rBa.getAccountNumber());
                    left.setReceiverBank(rBa.getBankName());
                    left.setReceiverName(receiver);
                    left.setSenderAccountNumber(baa.getAccountNumber());
                    left.setSenderBank(baa.getBankName());
                    left.setSenderName(baa.getCustomerName());
                    baa.getTransactionRecordDirectory().getFundsTransactionDirectory().add(left);
                    baa.setBalance(baa.getBalance() - amount);
                    right.setAccountNumber(rBa.getAccountNumber());
                    right.setCustomer(rBa.getCustomerName());
                    right.setDate(new Date());
                    right.setDirection("In");
                    right.setFee(amount);
                    right.setReceiverAccountNumber(rBa.getAccountNumber());
                    right.setReceiverBank(rBa.getBankName());
                    right.setReceiverName(receiver);
                    right.setSenderAccountNumber(baa.getAccountNumber());
                    right.setSenderBank(baa.getBankName());
                    right.setSenderName(baa.getCustomerName());
                    rBa.getTransactionRecordDirectory().getFundsTransactionDirectory().add(right);
                    rBa.setBalance(rBa.getBalance()+amount);
                } else {
                    JOptionPane.showMessageDialog(null, "The Bank Account is not macthed with the receiver you input!");
                }
            }
                
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Password!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTf;
    private javax.swing.JComboBox<String> anCombo1;
    private javax.swing.JTextField anTf;
    private javax.swing.JTextField bTf;
    private javax.swing.JComboBox<String> bnCombo1;
    private javax.swing.JTextField bnTf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pwTf;
    private javax.swing.JTextField rnTf;
    private javax.swing.JTextField snTf;
    // End of variables declaration//GEN-END:variables
}
